# Site settings
title: ntb. - Code, rants and rock'n'roll.
owner: Nils Torbjörn Butenschön, M.A.
email: moin@nilsbutenschoen.de
description: > # this means to ignore newlines until "baseurl:"
    Blog und digitale Visitenkarte von Nils Torbjörn Butenschön. Webentwickler, Musiker und ambitionierter Hobby-Fotograf aus Kiel an der schönen Ostseeküste.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nilsbutenschoen.de" # the base hostname & protocol for your site
twitter_username: DerNerddeutsche
github_username:  entepe85

# Build settings
markdown: kramdown
sass:
    style: compressed
